// Curated emoji for the Elements tab: [emoji, name, keywords].

export type EmojiEntry = [emoji: string, name: string, keywords: string]

export const EMOJI_CATEGORIES: Record<string, EmojiEntry[]> = {
  popular: [
    ["⭐","Star","star favorite rating"],
    ["🔥","Fire","fire hot trending"],
    ["❤️","Red Heart","heart love like"],
    ["✨","Sparkles","sparkles magic new"],
    ["🎉","Party Popper","party celebrate confetti"],
    ["🚀","Rocket","rocket launch fast speed"],
    ["💡","Light Bulb","idea bulb light tip"],
    ["✅","Check Mark","check done complete yes"],
    ["🎯","Bullseye","target goal aim bullseye"],
    ["💪","Flexed Bicep","strong muscle power flex"],
    ["👑","Crown","crown king queen royal best"],
    ["🏆","Trophy","trophy winner award champion"],
    ["💰","Money Bag","money rich dollar finance"],
    ["🎨","Artist Palette","art paint design creative"],
    ["📱","Mobile Phone","phone mobile smartphone app"],
    ["💻","Laptop","laptop computer work code"],
    ["🔒","Lock","lock secure private safe"],
    ["⚡","Lightning","lightning fast electric power zap"],
    ["🌟","Glowing Star","star glow bright shine"],
    ["💎","Gem","gem diamond premium jewel"],
    ["🔔","Bell","bell notification alert ring"],
    ["📊","Bar Chart","chart graph stats analytics"],
    ["🎵","Musical Note","music note song audio"],
    ["📸","Camera Flash","camera photo picture snap"],
    ["🌈","Rainbow","rainbow color pride beautiful"],
    ["💬","Speech Bubble","speech chat message talk"],
    ["🛡️","Shield","shield protect defense safe"],
    ["🎁","Gift","gift present surprise reward"],
    ["🔑","Key","key unlock access password"],
    ["📈","Chart Up","growth increase trending up"],
    ["❌","Cross Mark","cross no wrong delete cancel"],
    ["💯","Hundred","hundred perfect score 100"],
  ],
  smileys: [
    ["😀","Grinning","happy smile grin"],
    ["😃","Smiley","happy smile joy"],
    ["😄","Smile","happy smile glad"],
    ["😁","Beaming","grin happy teeth"],
    ["😆","Laughing","laugh lol happy"],
    ["😅","Sweat Smile","sweat nervous relief"],
    ["🤣","ROFL","rolling laugh lol"],
    ["😂","Joy","tears laugh funny"],
    ["🙂","Slight Smile","smile okay fine"],
    ["😉","Wink","wink flirt playful"],
    ["😊","Blush","blush happy warm"],
    ["😇","Halo","angel innocent good"],
    ["🥰","Love Face","love hearts adore"],
    ["😍","Heart Eyes","love heart wow"],
    ["🤩","Star Struck","stars amazing wow"],
    ["😘","Kissing","kiss love muah"],
    ["😎","Cool","cool sunglasses confident"],
    ["🤔","Thinking","think hmm consider"],
    ["🤗","Hugging","hug warm embrace"],
    ["🤯","Mind Blown","mind blown explode shocked"],
    ["😱","Screaming","scream shock fear"],
    ["🥳","Partying","party celebrate fun"],
    ["😴","Sleeping","sleep zzz tired"],
    ["🤫","Shushing","quiet secret shh"],
    ["🫡","Saluting","salute respect sir"],
    ["🤓","Nerd","nerd smart glasses"],
    ["😈","Devil","devil evil imp mischief"],
    ["👻","Ghost","ghost boo spooky"],
    ["🤖","Robot","robot ai machine"],
    ["👽","Alien","alien ufo space"],
  ],
  objects: [
    ["⌚","Watch","watch time wrist"],
    ["📱","Phone","phone mobile cell"],
    ["💻","Laptop","laptop computer"],
    ["⌨️","Keyboard","keyboard type input"],
    ["🖥️","Desktop","desktop monitor screen"],
    ["🖨️","Printer","printer print"],
    ["🖱️","Mouse","mouse click cursor"],
    ["💿","CD","cd disc dvd"],
    ["📷","Camera","camera photo"],
    ["🎥","Movie Camera","movie film video"],
    ["📺","Television","tv television screen"],
    ["📻","Radio","radio audio broadcast"],
    ["🎙️","Microphone","microphone podcast record"],
    ["🎧","Headphones","headphones music audio"],
    ["🔋","Battery","battery power charge"],
    ["🔌","Plug","plug power electric"],
    ["💡","Bulb","bulb idea light"],
    ["🔦","Flashlight","flashlight torch light"],
    ["📦","Package","package box ship delivery"],
    ["✉️","Envelope","envelope mail email letter"],
    ["📋","Clipboard","clipboard list paste"],
    ["📝","Memo","memo note write"],
    ["📁","Folder","folder file directory"],
    ["📅","Calendar","calendar date schedule"],
    ["📌","Pushpin","pin pushpin location"],
    ["📎","Paperclip","paperclip attach clip"],
    ["✂️","Scissors","scissors cut trim"],
    ["🔧","Wrench","wrench tool fix settings"],
    ["🔨","Hammer","hammer tool build"],
    ["⚙️","Gear","gear settings cog config"],
    ["🧲","Magnet","magnet attract"],
    ["🧪","Test Tube","test lab science experiment"],
    ["💊","Pill","pill medicine health"],
    ["🪙","Coin","coin money gold"],
    ["💳","Credit Card","credit card payment bank"],
    ["🛒","Shopping Cart","cart shopping buy"],
    ["🎮","Game Controller","game controller play gaming"],
    ["🕹️","Joystick","joystick game arcade"],
    ["🧩","Puzzle","puzzle piece jigsaw"],
  ],
  symbols: [
    ["❤️","Red Heart","heart love red"],
    ["🧡","Orange Heart","heart orange"],
    ["💛","Yellow Heart","heart yellow"],
    ["💚","Green Heart","heart green"],
    ["💙","Blue Heart","heart blue"],
    ["💜","Purple Heart","heart purple"],
    ["🖤","Black Heart","heart black"],
    ["🤍","White Heart","heart white"],
    ["💔","Broken Heart","heart broken sad"],
    ["♻️","Recycle","recycle green eco"],
    ["⚠️","Warning","warning alert caution"],
    ["🚫","Prohibited","no prohibited ban forbidden"],
    ["✅","Check","check done complete approved"],
    ["❌","Cross","cross no wrong cancel"],
    ["❓","Question","question ask help"],
    ["❗","Exclamation","exclamation alert important"],
    ["💲","Dollar","dollar money price"],
    ["🔴","Red Circle","red circle dot"],
    ["🟢","Green Circle","green circle dot online"],
    ["🔵","Blue Circle","blue circle dot"],
    ["🟡","Yellow Circle","yellow circle dot"],
    ["🟠","Orange Circle","orange circle dot"],
    ["🟣","Purple Circle","purple circle dot"],
    ["⬛","Black Square","black square"],
    ["⬜","White Square","white square"],
    ["🔶","Orange Diamond","orange diamond"],
    ["🔷","Blue Diamond","blue diamond"],
    ["▶️","Play","play start video"],
    ["⏸️","Pause","pause stop"],
    ["⏩","Fast Forward","forward fast skip"],
    ["🔀","Shuffle","shuffle random mix"],
    ["🔁","Repeat","repeat loop cycle"],
    ["➕","Plus","plus add new"],
    ["➖","Minus","minus subtract remove"],
    ["➡️","Right Arrow","arrow right next forward"],
    ["⬅️","Left Arrow","arrow left back"],
    ["⬆️","Up Arrow","arrow up"],
    ["⬇️","Down Arrow","arrow down"],
    ["↗️","Up-Right Arrow","arrow diagonal growth"],
    ["🔗","Link","link chain url"],
    ["♾️","Infinity","infinity forever loop"],
    ["©️","Copyright","copyright legal"],
    ["™️","Trademark","trademark brand"],
    ["®️","Registered","registered brand"],
  ],
  animals: [
    ["🐶","Dog","dog puppy pet"],
    ["🐱","Cat","cat kitten pet"],
    ["🐭","Mouse","mouse rodent"],
    ["🐹","Hamster","hamster pet"],
    ["🐰","Rabbit","rabbit bunny"],
    ["🦊","Fox","fox clever"],
    ["🐻","Bear","bear teddy"],
    ["🐼","Panda","panda bamboo"],
    ["🐨","Koala","koala australia"],
    ["🦁","Lion","lion king brave"],
    ["🐯","Tiger","tiger fierce"],
    ["🐮","Cow","cow milk farm"],
    ["🐷","Pig","pig oink farm"],
    ["🐸","Frog","frog toad"],
    ["🐵","Monkey","monkey ape"],
    ["🐔","Chicken","chicken hen farm"],
    ["🐧","Penguin","penguin cold ice"],
    ["🐦","Bird","bird tweet fly"],
    ["🦅","Eagle","eagle bird fly"],
    ["🦋","Butterfly","butterfly insect beautiful"],
    ["🐛","Bug","bug insect caterpillar"],
    ["🐝","Bee","bee honey buzz"],
    ["🐠","Fish","fish tropical sea"],
    ["🐬","Dolphin","dolphin sea smart"],
    ["🦄","Unicorn","unicorn magic fantasy"],
    ["🐉","Dragon","dragon fire fantasy"],
    ["🦈","Shark","shark sea danger"],
    ["🐙","Octopus","octopus sea tentacles"],
    ["🦉","Owl","owl wise night"],
    ["🐺","Wolf","wolf wild howl"],
  ],
  food: [
    ["🍎","Apple","apple fruit red"],
    ["🍊","Orange","orange fruit citrus"],
    ["🍋","Lemon","lemon fruit citrus sour"],
    ["🍌","Banana","banana fruit yellow"],
    ["🍇","Grapes","grapes fruit wine"],
    ["🍓","Strawberry","strawberry fruit berry"],
    ["🍑","Peach","peach fruit"],
    ["🍒","Cherry","cherry fruit red"],
    ["🥑","Avocado","avocado guac green"],
    ["🌶️","Hot Pepper","pepper hot spicy"],
    ["🍕","Pizza","pizza food slice"],
    ["🍔","Burger","burger hamburger food"],
    ["🍟","Fries","fries chips food"],
    ["🌮","Taco","taco food mexican"],
    ["🍩","Donut","donut doughnut sweet"],
    ["🍪","Cookie","cookie biscuit sweet"],
    ["🎂","Birthday Cake","cake birthday celebration"],
    ["🍰","Shortcake","cake dessert sweet"],
    ["🧁","Cupcake","cupcake muffin sweet"],
    ["☕","Coffee","coffee tea drink hot"],
    ["🍵","Tea","tea green drink"],
    ["🥤","Cup with Straw","drink soda cup"],
    ["🍺","Beer","beer drink cheers"],
    ["🍷","Wine","wine drink glass"],
    ["🥂","Clinking Glasses","cheers toast celebrate"],
    ["🧃","Juice Box","juice drink box"],
  ],
  travel: [
    ["🌍","Globe Europe","globe earth world europe"],
    ["🌎","Globe Americas","globe earth world america"],
    ["🌏","Globe Asia","globe earth world asia"],
    ["🗺️","World Map","map world travel"],
    ["🏠","House","house home building"],
    ["🏢","Office","office building work"],
    ["🏥","Hospital","hospital medical health"],
    ["🏫","School","school education learn"],
    ["🏛️","Classical Building","building classical museum"],
    ["⛪","Church","church religion building"],
    ["🗼","Tokyo Tower","tower tokyo japan"],
    ["🗽","Statue of Liberty","liberty statue nyc"],
    ["✈️","Airplane","airplane plane fly travel"],
    ["🚗","Car","car auto drive"],
    ["🚕","Taxi","taxi cab ride"],
    ["🚌","Bus","bus transit ride"],
    ["🚂","Train","train rail locomotive"],
    ["🚀","Rocket","rocket space launch"],
    ["🛸","UFO","ufo alien flying saucer"],
    ["⛵","Sailboat","sailboat boat sea"],
    ["🏖️","Beach","beach vacation sand"],
    ["🏔️","Mountain","mountain snow peak"],
    ["🌋","Volcano","volcano eruption lava"],
    ["🏕️","Camping","camping tent outdoor"],
    ["🎡","Ferris Wheel","ferris wheel amusement"],
    ["🌅","Sunrise","sunrise morning dawn"],
    ["🌄","Sunrise Over Mountains","sunrise mountain morning"],
    ["🌃","Night City","night city stars"],
    ["🌙","Crescent Moon","moon night crescent"],
    ["☀️","Sun","sun sunny bright day"],
    ["⛅","Partly Cloudy","cloud sun weather"],
    ["🌊","Wave","wave ocean sea water"],
    ["❄️","Snowflake","snow cold winter ice"],
  ],
  flags: [
    ["🇺🇸","US","us usa america united states"],
    ["🇬🇧","UK","uk britain united kingdom england"],
    ["🇩🇪","Germany","germany deutsch"],
    ["🇫🇷","France","france french"],
    ["🇪🇸","Spain","spain spanish"],
    ["🇮🇹","Italy","italy italian"],
    ["🇯🇵","Japan","japan japanese"],
    ["🇰🇷","South Korea","korea korean"],
    ["🇨🇳","China","china chinese"],
    ["🇧🇷","Brazil","brazil brazilian"],
    ["🇮🇳","India","india indian"],
    ["🇷🇺","Russia","russia russian"],
    ["🇨🇦","Canada","canada canadian"],
    ["🇦🇺","Australia","australia australian"],
    ["🇲🇽","Mexico","mexico mexican"],
    ["🇳🇱","Netherlands","netherlands dutch holland"],
    ["🇸🇪","Sweden","sweden swedish"],
    ["🇳🇴","Norway","norway norwegian"],
    ["🇩🇰","Denmark","denmark danish"],
    ["🇫🇮","Finland","finland finnish"],
    ["🇵🇱","Poland","poland polish"],
    ["🇵🇹","Portugal","portugal portuguese"],
    ["🇹🇷","Turkey","turkey turkish"],
    ["🇸🇦","Saudi Arabia","saudi arabia"],
    ["🇦🇪","UAE","uae dubai emirates"],
    ["🇹🇭","Thailand","thailand thai"],
    ["🇻🇳","Vietnam","vietnam vietnamese"],
    ["🇮🇩","Indonesia","indonesia indonesian"],
    ["🇵🇭","Philippines","philippines filipino"],
    ["🇳🇬","Nigeria","nigeria nigerian"],
    ["🇿🇦","South Africa","south africa"],
    ["🇦🇷","Argentina","argentina"],
    ["🇨🇱","Chile","chile chilean"],
    ["🇨🇴","Colombia","colombia colombian"],
    ["🏴","Black Flag","flag black"],
    ["🏳️","White Flag","flag white surrender"],
    ["🏁","Checkered Flag","flag finish race"],
    ["🚩","Red Flag","flag red warning"],
    ["🏳️‍🌈","Rainbow Flag","rainbow pride lgbtq"],
  ],
}

export function searchEmoji(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase()
  if (!q) return EMOJI_CATEGORIES.popular
  const seen = new Set<string>()
  const out: EmojiEntry[] = []
  for (const list of Object.values(EMOJI_CATEGORIES)) for (const e of list) {
    if (!seen.has(e[0]) && (e[1].toLowerCase().includes(q) || e[2].includes(q))) { seen.add(e[0]); out.push(e) }
  }
  return out
}
