import { SPEC_REVIEWED } from '../lib/model/platforms'
import type { Guide } from './types'

const UPDATED = SPEC_REVIEWED

export const GUIDES: Guide[] = [
  // ------------------------------------------------------------------------
  {
    slug: 'app-store-screenshot-sizes',
    title: 'App Store screenshot sizes and requirements (2026)',
    description: 'Every App Store Connect screenshot size for iPhone, iPad, Mac, Apple TV, Vision Pro and Apple Watch — which ones are required, formats, limits and tips.',
    category: 'Store requirements',
    updated: UPDATED,
    readMinutes: 7,
    summary: [
      'Upload **6.9" iPhone** screenshots (1320 × 2868) — App Store Connect scales them down for smaller iPhones. 6.5" is the fallback if you skip 6.9".',
      'iPad apps need **13" iPad** screenshots (2064 × 2752 or 2048 × 2732).',
      'Up to **10 screenshots** per device size and localization, PNG or JPEG, **no transparency**.',
      'Mac uses 16:10 (up to 2880 × 1800); Apple TV and Vision Pro use 3840 × 2160.',
    ],
    blocks: [
      { t: 'p', text: 'App Store Connect accepts a fixed list of pixel sizes per device class. Uploading anything else is rejected, so it pays to design at the right size from the start. The good news: you only have to design **one iPhone size and one iPad size** — Apple downsizes them for older devices.' },
      { t: 'h2', text: 'iPhone screenshot sizes' },
      { t: 'p', text: 'The 6.9" display class (iPhone 16/17 Pro Max, iPhone Air and friends) is the one to design for. If you do not provide 6.9" screenshots, the 6.5" class becomes required instead.' },
      { t: 'sizes', platformIds: ['app-store-iphone'] },
      { t: 'callout', tone: 'tip', text: 'Pick **1320 × 2868** unless you have a reason not to. Storedeck starts every iPhone platform at that size, and you can switch to landscape per platform for games.' },
      { t: 'h2', text: 'iPad screenshot sizes' },
      { t: 'p', text: 'If your app runs on iPad, 13" screenshots are required. Use real iPad captures — stretching iPhone screenshots onto an iPad canvas is one of the most common reasons listings look low-effort.' },
      { t: 'sizes', platformIds: ['app-store-ipad'] },
      { t: 'h2', text: 'Mac, Apple TV, Vision Pro and Apple Watch' },
      { t: 'sizes', platformIds: ['app-store-mac', 'app-store-apple-tv', 'app-store-vision-pro', 'app-store-watch'] },
      { t: 'ul', items: ['Mac screenshots are always **16:10**. A window-style frame (title bar with traffic lights) makes captures read as a desktop app instantly.', 'Apple TV screenshots should show the focus-driven interface at a 10-foot distance — keep overlays large and minimal.', 'Apple Watch screenshots must use the **same size across all localizations**.'] },
      { t: 'h2', text: 'File rules that trip people up' },
      { t: 'ul', items: ['**No alpha channel.** Transparent PNGs are rejected. Storedeck flattens exports onto the background, and JPEG export is always opaque.', 'PNG or JPEG only, RGB color.', '1 to 10 screenshots per device size and per localization. Missing localizations fall back to your primary language set.', 'App Review guideline 2.3.3 asks that screenshots **show the app in use** — not just title art, a login page or a splash screen. Text and image overlays are fine.'] },
      { t: 'h2', text: 'Which screenshots people actually see' },
      { t: 'p', text: 'In search results the App Store shows your first screenshots (or your app preview video) right under the app name. Treat screenshots 1–3 as the ad: they carry your core value proposition, and everything after that is for people who already tapped in. See [writing screenshot headlines that convert](/guides/screenshot-copywriting).' },
      { t: 'h2', text: 'Making the full set in Storedeck' },
      { t: 'ol', items: ['Create a project and pick **iPhone** (and **iPad** if needed) as platforms.', 'Drop your simulator captures in. Files named `home_de.png` automatically become the German version of `home.png`.', 'Write headlines per language, pick a background and a device frame, then **Apply to all screens**.', 'Add the iPad platform with **Start from: iPhone** — screens, copy and design are copied and rescaled.', 'Export a ZIP laid out as `platform/language/01-name.png`, ready to drag into App Store Connect.'] },
    ],
    faqs: [
      { q: 'Do I need screenshots for every iPhone size?', a: 'No. Provide the 6.9" size (or 6.5") and App Store Connect scales it for smaller displays. You can still upload smaller sizes if you want pixel-perfect sets.' },
      { q: 'Can I upload landscape iPhone screenshots?', a: 'Yes — every iPhone and iPad size is also accepted rotated. Keep one orientation within a set so the listing looks consistent.' },
      { q: 'Why was my PNG rejected?', a: 'The most common cause is an alpha channel. Export as JPEG or a flattened PNG; Storedeck exports never contain transparency.' },
    ],
    related: ['google-play-screenshot-requirements', 'screenshot-copywriting', 'localize-app-store-screenshots'],
  },
  // ------------------------------------------------------------------------
  {
    slug: 'google-play-screenshot-requirements',
    title: 'Google Play screenshot requirements: phones, tablets, Chromebook, TV and Wear OS',
    description: 'Google Play screenshot sizes, aspect-ratio rules, promotion eligibility, feature graphic and TV banner specs — with ready-made sizes for every device type.',
    category: 'Store requirements',
    updated: UPDATED,
    readMinutes: 7,
    summary: [
      'Phone screenshots: **320–3,840 px** per side, long side at most **2× the short side**, JPEG or 24-bit PNG without alpha.',
      'For promotion eligibility add **at least 4 screenshots ≥ 1080 px** in **9:16** portrait (or 16:9 landscape).',
      'Tablets and Chromebooks: 1,080–7,680 px, 16:9 or 9:16, at least 4 to be featured on large screens.',
      'Up to **8 screenshots per device type**. Plus a **1024 × 500 feature graphic**, and a **1280 × 720 banner** for TV.',
    ],
    blocks: [
      { t: 'p', text: 'Google Play is more flexible than the App Store about exact pixel sizes, but it rewards specific aspect ratios: listings that follow the 9:16 / 16:9 recommendations are eligible for richer placements in the store. Design to those ratios and you never have to think about it again.' },
      { t: 'h2', text: 'Phone screenshots' },
      { t: 'sizes', platformIds: ['google-play-phone'] },
      { t: 'ul', items: ['Any size between 320 and 3,840 px per side is accepted, as long as the longer side is no more than twice the shorter.', '**1080 × 1920** is the practical default: it meets the 1080 px promotion threshold at exactly 9:16.', 'You need at least 2 screenshots overall to publish, and at least 4 for promotion eligibility.'] },
      { t: 'h2', text: 'Tablets and Chromebooks' },
      { t: 'p', text: 'Google treats 7" tablets, 10" tablets and Chromebooks as large-screen devices. Screenshots must be between 1,080 and 7,680 px with a 16:9 or 9:16 ratio.' },
      { t: 'sizes', platformIds: ['google-play-tablet-7', 'google-play-tablet-10', 'google-play-chromebook'] },
      { t: 'h2', text: 'Android TV, Wear OS, Android XR and Automotive' },
      { t: 'sizes', platformIds: ['google-play-tv', 'google-play-wear', 'google-play-xr', 'google-play-automotive'] },
      { t: 'ul', items: ['Android TV apps need at least one TV screenshot and a **1280 × 720 TV banner**.', 'Wear OS screenshots are **square (1:1)**, at least 384 × 384, and should show only your app UI.', 'Android XR uses an **8:5** ratio — 3840 × 2400 recommended.'] },
      { t: 'h2', text: 'Feature graphic' },
      { t: 'p', text: 'The **1024 × 500** feature graphic appears at the top of your listing and in promotional placements. Keep text and logos away from the edges because it can be cropped, and do not rely on it to explain your app — many surfaces show it without your screenshots.' },
      { t: 'sizes', platformIds: ['google-play-artwork'] },
      { t: 'h2', text: 'Content guidance' },
      { t: 'ul', items: ['Avoid ranking or price claims ("#1", "Best", "Free", "Sale") and calls to action like "Download now" in store graphics — Google\'s listing guidelines discourage them and they can get a listing flagged.', 'Screenshots should represent the actual in-app experience on the device type they are uploaded for.', 'Localize: Play Console lets you add graphics per language, and unlocalized languages fall back to your default graphics.'] },
      { t: 'h2', text: 'From iPhone to Android in two clicks' },
      { t: 'p', text: 'In Storedeck, add the **Android phone** platform and choose **Start from: iPhone**. Screens, headlines and design are copied and rescaled to 1080 × 1920; then replace the screenshots with Android captures (drop files with the same names and they land on the right screens). Want a Galaxy look? Switch the device to the 3D Galaxy S25 Ultra model.' },
    ],
    faqs: [
      { q: 'What is the best Google Play screenshot size?', a: '1080 × 1920 (9:16) for phones. It is accepted everywhere, meets the promotion threshold and keeps file sizes reasonable. Use 1440 × 2560 or 2160 × 3840 if you want extra sharpness.' },
      { q: 'How many screenshots can I upload to Google Play?', a: 'Up to 8 per device type (phone, 7" tablet, 10" tablet, Chromebook, TV, Wear OS, XR). At least 2 are needed overall to publish; 4 or more for promotion eligibility.' },
      { q: 'Do Google Play screenshots need a device frame?', a: 'No. Frames are optional — what matters is that the screenshot shows the real app. A subtle phone frame often helps readability; for Wear OS keep captures plain.' },
    ],
    related: ['app-store-screenshot-sizes', 'tv-app-store-screenshots', 'ab-testing-store-screenshots'],
  },
  // ------------------------------------------------------------------------
  {
    slug: 'ab-testing-store-screenshots',
    title: 'A/B testing App Store and Google Play screenshots',
    description: 'How to run screenshot experiments with App Store Product Page Optimization and Google Play store listing experiments — what to test, how long, and how to prepare variants.',
    category: 'Strategy',
    updated: UPDATED,
    readMinutes: 8,
    summary: [
      'Apple **Product Page Optimization**: up to **3 treatments** against your original page, one test at a time, up to **90 days**.',
      'Google Play **store listing experiments**: up to **2 variants** vs. the current listing; one default-graphics experiment or up to **5 localized** experiments at once.',
      'Test one idea per variant — headline angle, first screenshot, visual style or order — so a result tells you something.',
      'In Storedeck each **variant** is a full copy of your screenshots across platforms and languages, tracked with a status and hypothesis.',
    ],
    blocks: [
      { t: 'p', text: 'Screenshots are the biggest lever on store conversion that you fully control. Both major stores let you test alternatives against your live listing with real traffic — but the tools differ, and a test is only as good as the variants you feed it.' },
      { t: 'h2', text: 'Apple: Product Page Optimization (PPO)' },
      { t: 'ul', items: ['Test **up to three treatments** against your original product page. You can vary screenshots, app previews and app icons.', 'Only **one test runs at a time**, for **up to 90 days**. You choose what share of traffic sees treatments; it is split evenly between them, and each visitor keeps seeing the same version.', 'New screenshots in a treatment go through App Review before the test starts (icon tests also require the icons in your app binary).', 'Treatments can be localized for all or some of your languages — more localizations can mean longer tests to reach significance.', 'Apple reports conversion rate and improvement with a confidence level; wait for high confidence (Apple suggests at least 90%) before applying a winner.'] },
      { t: 'h2', text: 'Google Play: store listing experiments' },
      { t: 'ul', items: ['Test **up to two variants** against your current listing, with an adjustable share of visitors split equally across variants.', '**Default graphics experiments** test the icon, feature graphic and screenshots in your default language — one at a time.', '**Localized experiments** can also test descriptions, and you can run **up to five** at once in different languages.', 'Pick a target metric such as install clicks; Play Console estimates how long the test needs, and experiments stop automatically after six months.'] },
      { t: 'h2', text: 'What to test (in rough order of impact)' },
      { t: 'ol', items: ['**The first screenshot** — it does most of the work in search results. Test a benefit headline vs. a feature headline, or a hero shot vs. a UI capture.', '**Headline angle** across the set: outcome ("Sleep better tonight") vs. mechanism ("Smart sleep tracking").', '**Order** — lead with the feature your best reviews mention.', '**Visual style** — light vs. dark backgrounds, frames vs. frameless, 2D vs. 3D devices.', '**Social proof** — award badges or ratings as overlay elements.'] },
      { t: 'callout', tone: 'warn', text: 'Change **one idea per variant**. If variant B has new copy, new colors and a new order, a win tells you nothing you can reuse.' },
      { t: 'h2', text: 'Preparing variants in Storedeck' },
      { t: 'ol', items: ['Mark your live set as **control**: open the variant menu and set its status.', 'Click **+** next to the variant tabs. The new variant is a full copy of the current one — every platform, screen, language and image.', 'Write the **hypothesis** ("Outcome-led headlines lift installs") and change only what the test is about.', 'Use the **Compare** view to see variants side by side for the same platform and language, exactly as a shopper would scan them.', 'Export: pick the variants, platforms and languages in the export dialog. Files are grouped as `variant/platform/language/NN-name.png`, ready for PPO treatments or Play experiment variants.', 'When the store declares a result, set that variant to **winner** — the previous control is demoted automatically, so the project always shows what is live.'] },
      { t: 'h2', text: 'How long should a screenshot test run?' },
      { t: 'p', text: 'Long enough to cover at least one full week (weekday and weekend traffic behave differently) and to reach the confidence the store reports as reliable. Low-traffic apps should test bold differences — subtle tweaks need huge samples. Avoid running tests during feature placements or big marketing pushes, which skew who visits your page.' },
    ],
    faqs: [
      { q: 'How many screenshot variants can I test on the App Store?', a: 'Up to three treatments against the original product page, with one test running at a time for up to 90 days.' },
      { q: 'How many variants does Google Play allow?', a: 'Up to two variants against the current listing per experiment. You can run one default-graphics experiment, or up to five localized experiments simultaneously.' },
      { q: 'Can I test screenshots in only some languages?', a: 'Yes. Apple lets treatments cover all or selected localizations, and Google Play offers localized experiments per language. In Storedeck, variants contain every language, and you choose which to export.' },
    ],
    related: ['screenshot-copywriting', 'app-store-screenshot-sizes', 'google-play-screenshot-requirements'],
  },
  // ------------------------------------------------------------------------
  {
    slug: 'localize-app-store-screenshots',
    title: 'How to localize App Store and Google Play screenshots',
    description: 'A practical workflow for localized store screenshots: which languages to start with, file naming, long German words, RTL Arabic and Hebrew, CJK line breaks and fonts.',
    category: 'Localization',
    updated: UPDATED,
    readMinutes: 7,
    summary: [
      'Localize the **copy first**, then the **screenshots themselves** for your biggest markets — translated text over English UI still converts better than nothing.',
      'Name files `screen_de.png`, `screen-pt-br.png`: Storedeck groups them onto the right screen automatically.',
      'Give long languages (German, Finnish) and short ones (Japanese, Chinese) their own **per-language layout** instead of shrinking everything.',
      'Right-to-left languages mirror alignment automatically; pick fonts that cover the script (Noto families are a safe bet).',
    ],
    blocks: [
      { t: 'p', text: 'Shoppers scan screenshots in a split second, and they scan faster in their own language. Localized screenshots are one of the cheapest conversion wins available — especially on Google Play, where most installs come from outside English-speaking markets.' },
      { t: 'h2', text: 'Decide what to localize' },
      { t: 'ol', items: ['**Headlines and subheadlines** — always. They are short, cheap to translate and carry the pitch.', '**The screenshots themselves** — for your top markets. Capture the app in each language (simulators and emulators make this scriptable).', '**Imagery and examples** — currencies, names, maps and dates that feel local. Nice to have.'] },
      { t: 'h2', text: 'Organize files by language' },
      { t: 'p', text: 'Storedeck detects language suffixes in file names: `home.png`, `home_de.png`, `home-pt-br.png` and `home_ja.png` all become versions of the same **home** screen. Missing languages fall back to your default language, and the **Board** view shows every screen × language combination at once so gaps stand out.' },
      { t: 'callout', tone: 'tip', text: 'Keep the file stem identical across languages (`01-dictate_en.png`, `01-dictate_te.png`) and upload them all at once — Storedeck sorts them onto the right screens.' },
      { t: 'h2', text: 'Translate in a strings table' },
      { t: 'p', text: 'The **Strings** view is a spreadsheet of every headline, subheadline and text badge per language, with missing translations highlighted. Translators can work there directly, or an AI agent can fill it using the `get_strings` and `set_copy` WebMCP tools — see [automating with AI agents](/guides/automate-store-screenshots-with-ai-agents).' },
      { t: 'h2', text: 'Long words, short scripts' },
      { t: 'ul', items: ['German, Finnish and Dutch run 20–35% longer than English and have long compound words. Instead of shrinking every language, turn on **custom sizes for this language** in the text panel and give it a slightly smaller size or more lines.', 'Japanese, Chinese and Korean are compact; the same headline can go larger. Storedeck wraps CJK and Thai text at proper word boundaries rather than overflowing.', 'Use manual line breaks (`\\n`) in copy for deliberate phrasing — they are kept per language.'] },
      { t: 'h2', text: 'Right-to-left languages' },
      { t: 'p', text: 'For Arabic, Hebrew, Persian and Urdu, text is rendered right-to-left and left/right alignment mirrors automatically. Consider mirroring layouts that point toward the device (arrows, side-by-side text) too, and capture the app in its RTL layout.' },
      { t: 'h2', text: 'Fonts that cover the script' },
      { t: 'p', text: 'Many display fonts only cover Latin. When a glyph is missing, the browser falls back to a system font, which can look inconsistent. Pick a family with broad coverage — **Noto Sans** has variants for Japanese, Korean, Chinese, Arabic, Hebrew, Devanagari, Telugu, Tamil, Bengali and Thai — or set a different font per screen set for those markets.' },
      { t: 'h2', text: 'Which languages first?' },
      { t: 'p', text: 'Start with the languages where you already have traffic (App Store Connect and Play Console show impressions by country), then the large markets that respond most to localization: Japanese, German, French, Spanish, Brazilian Portuguese, Korean and Simplified Chinese. For India-focused apps, Hindi plus one or two regional languages (Telugu, Tamil, Bengali) often outperform English-only listings.' },
    ],
    faqs: [
      { q: 'Do I have to upload separate screenshots for each App Store language?', a: 'No. Localizations without their own screenshots show your primary language screenshots. Upload localized sets for the markets where it matters.' },
      { q: 'How do I handle languages my font does not support?', a: 'Choose a font with wider script coverage (Noto families), or override the font for that language\'s screens. Storedeck previews every language on the Board view so fallbacks are easy to spot.' },
    ],
    related: ['screenshot-copywriting', 'automate-store-screenshots-with-ai-agents', 'app-store-screenshot-sizes'],
  },
  // ------------------------------------------------------------------------
  {
    slug: 'tv-app-store-screenshots',
    title: 'TV app screenshots: Apple TV, Android TV, Fire TV and Xbox',
    description: 'Screenshot sizes and design tips for TV storefronts — Apple TV (tvOS), Android TV / Google TV, Amazon Fire TV, Xbox and smart TV stores.',
    category: 'Store requirements',
    updated: UPDATED,
    readMinutes: 6,
    summary: [
      'Every TV store is **16:9**: 1920 × 1080 everywhere, 3840 × 2160 where 4K is accepted (Apple TV, Android TV, Xbox).',
      'Fire TV wants **3 to 10** screenshots at exactly 1920 × 1080; Android TV needs at least one plus a **1280 × 720 banner**.',
      'Design for the couch: big type, few words, and the focused state visible.',
    ],
    blocks: [
      { t: 'p', text: 'TV storefronts are viewed from three meters away with a remote. Screenshots that work on a phone — dense UI, small captions — turn into noise on a TV. The specs are simple; the design discipline is what matters.' },
      { t: 'h2', text: 'Sizes per TV store' },
      { t: 'sizes', platformIds: ['app-store-apple-tv', 'google-play-tv', 'amazon-fire-tv', 'ms-store-xbox', 'smart-tv'] },
      { t: 'h2', text: 'Design for ten feet' },
      { t: 'ul', items: ['Keep headlines to **3–5 words** and at least ~6% of the image height. Storedeck scales TV headline sizes from the canvas automatically.', 'Show the **focused** element — the lifted poster or highlighted row — so it is obvious the app is navigable with a remote.', 'Avoid thin fonts and pure white on light imagery; TVs vary wildly in brightness and overscan.', 'Leave margins: some TV storefronts crop or overlay the edges. Turn on **safe-area guides** in the editor.'] },
      { t: 'h2', text: 'Frame or full-bleed?' },
      { t: 'p', text: 'For TV, a full-bleed capture with a gradient scrim and a short headline usually beats a framed TV-inside-a-TV. Storedeck\'s TV frame is useful for marketing material and mixed sets (for example a phone companion app next to the TV app). Use the **TV** or **None** device frame per screen.' },
      { t: 'h2', text: 'Reuse your mobile work' },
      { t: 'p', text: 'Add a TV platform with **Start from** your phone platform to carry over copy, languages and brand styling, then drop in your TV captures with the same file names. Headline sizes and shadows rescale to the new canvas automatically.' },
    ],
    faqs: [
      { q: 'What size are Apple TV screenshots?', a: '1920 × 1080 or 3840 × 2160 (16:9).' },
      { q: 'What size are Fire TV screenshots?', a: 'Exactly 1920 × 1080 landscape, JPG or 24-bit PNG without transparency, with 3 to 10 screenshots.' },
    ],
    related: ['desktop-app-store-screenshots', 'google-play-screenshot-requirements'],
  },
  // ------------------------------------------------------------------------
  {
    slug: 'desktop-app-store-screenshots',
    title: 'Desktop store screenshots: Mac App Store, Microsoft Store and Steam',
    description: 'Screenshot sizes and layout advice for desktop storefronts — Mac App Store (16:10), Microsoft Store (up to 4K), Steam screenshots and capsule art, and Chromebooks.',
    category: 'Store requirements',
    updated: UPDATED,
    readMinutes: 7,
    summary: [
      'Mac App Store: **16:10** only — 1280 × 800 up to **2880 × 1800**.',
      'Microsoft Store: **1366 × 768 or larger** (up to 4K), up to 10 desktop screenshots; keep key content in the **top two-thirds**.',
      'Steam: screenshots **≥ 1920 × 1080** at 16:9, at least 5; capsules have fixed sizes such as **920 × 430** (header).',
    ],
    blocks: [
      { t: 'p', text: 'Desktop listings get far less design attention than mobile ones, which makes them an easy place to stand out. Wide canvases also allow layouts phones cannot: text beside the product instead of above it.' },
      { t: 'h2', text: 'Mac App Store' },
      { t: 'sizes', platformIds: ['app-store-mac'] },
      { t: 'p', text: 'Mac screenshots must be 16:10. Capture a clean window (hide personal data and busy desktops) and present it in an **app window** frame with a title bar, on a calm background.' },
      { t: 'h2', text: 'Microsoft Store (Windows)' },
      { t: 'sizes', platformIds: ['ms-store-desktop'] },
      { t: 'ul', items: ['PNG, up to 50 MB each; only one screenshot is required, up to 10 for desktop.', 'The Store can overlay text on the **bottom third** — keep headlines and key UI in the top two-thirds. Storedeck\'s safe-area guides shade that zone on Microsoft Store platforms.', 'Captions (up to 200 characters) are entered in Partner Center per language, separately from the image.'] },
      { t: 'h2', text: 'Steam' },
      { t: 'sizes', platformIds: ['steam-screenshots', 'steam-capsules'] },
      { t: 'p', text: 'Steam expects real gameplay in screenshots, so keep overlays light or skip them. Capsules are where branding goes: use a blank screen in a **Steam capsules** platform with your key art as a background image and your logo as an image element.' },
      { t: 'h2', text: 'Chromebooks' },
      { t: 'p', text: 'Google Play lists Chromebook screenshots separately: 16:9 (or 9:16), between 1,080 and 7,680 px. A laptop frame signals "works on Chromebook" at a glance.' },
      { t: 'h2', text: 'Layouts that work on wide canvases' },
      { t: 'ul', items: ['**Text left, product right** — choose the *Text left, device right* layout preset. Left-aligned copy is easier to read at desktop scale.', 'Window or browser frames give context without the weight of a full laptop.', 'For multi-window apps, use a popout to magnify the one panel that matters.'] },
    ],
    faqs: [
      { q: 'What size should Mac App Store screenshots be?', a: 'One of 1280 × 800, 1440 × 900, 2560 × 1600 or 2880 × 1800 — all 16:10. 2880 × 1800 looks sharpest on Retina displays.' },
      { q: 'What is the Microsoft Store screenshot size?', a: 'Desktop screenshots must be at least 1366 × 768 and can go up to 3840 × 2160. 1920 × 1080 is a good default.' },
    ],
    related: ['tv-app-store-screenshots', 'app-store-screenshot-sizes'],
  },
  // ------------------------------------------------------------------------
  {
    slug: 'screenshot-copywriting',
    title: 'Writing store screenshot headlines that convert',
    description: 'A practical playbook for App Store and Google Play screenshot copy: the first-three rule, benefit-first headlines, sequencing, readability and what to avoid.',
    category: 'Strategy',
    updated: UPDATED,
    readMinutes: 6,
    summary: [
      'Screenshot 1 is your ad: **one benefit, 2–5 words**, readable at thumbnail size.',
      'Each screen tells a **different** part of the story; together they answer "why this app?".',
      'Headline = outcome, subheadline = how. Cut every word that does not earn its place.',
    ],
    blocks: [
      { t: 'p', text: 'Most people decide whether to install from search results, where your screenshots are about the size of a stamp. Copy that works there is short, concrete and about the user — not the feature list.' },
      { t: 'h2', text: 'The first-three rule' },
      { t: 'p', text: 'Search results and browse surfaces show the first screenshots before anyone opens your page. Put your strongest reason to install on screenshot 1, your second-strongest on 2, and social proof or a differentiator on 3.' },
      { t: 'h2', text: 'Headline formulas that work' },
      { t: 'table', head: ['Formula', 'Example'], rows: [['Outcome', '**Sleep better tonight**'], ['Verb + object', '**Track every habit**'], ['Pain removed', '**No more lost receipts**'], ['Proof', '**Loved by 2M runners**'], ['Contrast', '**Just speak. Veena types.**']] },
      { t: 'ul', items: ['Keep headlines to **2–5 words**; subheadlines to **4–10 words** that explain how.', 'Use the words your reviews use. If users say "simple", do not write "intuitive".', 'Make each screen about one idea; if you need "and", you need another screenshot.'] },
      { t: 'h2', text: 'Readability checklist' },
      { t: 'ul', items: ['On phones, make the headline at least ~7% of the canvas width (about 90–110 px on a 1320 px-wide iPhone canvas).', 'Strong contrast — test on both light and dark backgrounds, and check the thumbnail.', 'No more than two lines for headlines in your longest language (use per-language sizes rather than a tiny global size).', 'Avoid tiny UI text as the focal point; magnify it with a popout instead.'] },
      { t: 'callout', tone: 'tip', text: 'Storedeck\'s `get_screen` tool (and the canvas warnings) flag headlines wrapping to more than three lines or colliding with the device frame — useful when an AI agent writes the copy.' },
      { t: 'h2', text: 'What to avoid' },
      { t: 'ul', items: ['Ranking and price claims ("#1", "Best", "Free!") — stores discourage them and they age badly.', 'Screenshots that are only text or a splash screen — Apple\'s guidelines ask that screenshots show the app in use.', 'Different fonts and styles on every screen. Pick one system and use **Apply to all screens**.'] },
      { t: 'h2', text: 'Then test it' },
      { t: 'p', text: 'Copy is the easiest variable to A/B test. Duplicate your set as a variant, rewrite the headlines around outcomes, and run it through App Store Product Page Optimization or a Play store listing experiment. See [A/B testing store screenshots](/guides/ab-testing-store-screenshots).' },
    ],
    related: ['ab-testing-store-screenshots', 'localize-app-store-screenshots'],
  },
  // ------------------------------------------------------------------------
  {
    slug: 'automate-store-screenshots-with-ai-agents',
    title: 'Automate store screenshots with AI agents (WebMCP)',
    description: 'Let Claude, ChatGPT or any WebMCP-capable agent design, localize, A/B test and export your App Store and Google Play screenshots with Storedeck\'s 22 site tools.',
    category: 'Automation',
    updated: UPDATED,
    readMinutes: 6,
    summary: [
      'Storedeck registers **22 WebMCP tools** covering every editor feature: projects, variants, platforms, screens, languages, copy, design, elements, popouts, views, undo and export.',
      'Agents review their work with **rendered previews** and layout warnings, then export full-resolution PNGs.',
      'Drop the [agent instructions](/agents#agents-md) into your repo\'s `AGENTS.md` and ask your coding agent to "update the store screenshots".',
    ],
    blocks: [
      { t: 'p', text: '[WebMCP](https://webmachinelearning.github.io/webmcp/) lets a web page expose tools to AI agents running in the browser. Instead of clicking through the UI, an agent calls typed functions — `manage_screens`, `set_copy`, `export` — and the editor updates live while you watch.' },
      { t: 'h2', text: 'What an agent can do' },
      { t: 'ul', items: ['Create a project, add platforms (iPhone, iPad, Android, Mac, TV…) and upload simulator screenshots as data URLs.', 'Look at the captures (`get_images` with `mode: "original"`), write headlines, and translate them into every project language in one `set_copy` call.', 'Style backgrounds, device frames (2D chrome or 3D iPhone/Galaxy), typography and per-language layouts.', 'Create **A/B variants**, copy designs across platforms, and compare them.', 'Check its own work: `get_images` renders the real composition; `get_screen` reports overlaps and overflowing text.', 'Export full-resolution PNGs per variant, platform and language — or build a ZIP for you.'] },
      { t: 'h2', text: 'A typical run' },
      { t: 'code', lang: 'text', code: '1. get_app_state                      → projects, variants, platforms, selection, hints\n2. manage_project  { action: "create", name: "Veena", platformIds: ["app-store-iphone", "google-play-phone"] }\n3. manage_screens  { action: "upload", screenshots: [{ filename: "01-dictate.png", dataUrl: "data:image/png;base64,…" }] }\n4. get_images      { mode: "original", scope: "platform" }\n5. set_copy        { entries: [{ screenIndex: 0, field: "headline", language: "en", text: "Just speak. Veena types." }, …] }\n6. set_background  { scope: "variant", gradientPreset: "Morning Mist" }\n7. set_text_style  { scope: "variant", headline: { font: "Plus Jakarta Sans", weight: "800", color: "#1c1c28" } }\n8. get_images      { scope: "platform" }   → review, fix warnings from get_screen\n9. export          { allLanguages: true, allPlatforms: true, delivery: "return" }' },
      { t: 'h2', text: 'Using it from a coding agent' },
      { t: 'p', text: 'Browser-automation agents (for example [agent-browser](https://github.com/vercel-labs/agent-browser) or a WebMCP-enabled Chrome) can open storedeck.byanr.com and call the tools directly. For agents that can only evaluate JavaScript, the same tools are available as `window.storedeck.callTool(name, input)`.' },
      { t: 'p', text: 'Add the snippet from the [agents page](/agents#agents-md) to your repository\'s `AGENTS.md` so every coding agent knows the workflow: capture simulator screenshots, open Storedeck, design, ask you for feedback, export, and save the files next to your code.' },
      { t: 'callout', tone: 'note', text: 'Everything runs in your browser. Screenshots and projects are stored locally in IndexedDB — nothing is uploaded to a Storedeck server.' },
    ],
    related: ['localize-app-store-screenshots', 'screenshot-copywriting'],
  },
]

export function getGuide(slug: string): Guide | undefined {
  return GUIDES.find(g => g.slug === slug)
}
