/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as ScreenshotSizesIndexRouteImport } from './routes/screenshot-sizes/index'
import { Route as ScreenshotSizesStoreRouteImport } from './routes/screenshot-sizes/$store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotSizesIndexRoute = ScreenshotSizesIndexRouteImport.update({
  id: '/screenshot-sizes/',
  path: '/screenshot-sizes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotSizesStoreRoute = ScreenshotSizesStoreRouteImport.update({
  id: '/screenshot-sizes/$store',
  path: '/screenshot-sizes/$store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/agents': typeof AgentsRoute
  '/editor': typeof EditorRoute
  '/faq': typeof FaqRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/screenshot-sizes/$store': typeof ScreenshotSizesStoreRoute
  '/guides/': typeof GuidesIndexRoute
  '/screenshot-sizes/': typeof ScreenshotSizesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/agents': typeof AgentsRoute
  '/editor': typeof EditorRoute
  '/faq': typeof FaqRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/screenshot-sizes/$store': typeof ScreenshotSizesStoreRoute
  '/guides': typeof GuidesIndexRoute
  '/screenshot-sizes': typeof ScreenshotSizesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/agents': typeof AgentsRoute
  '/editor': typeof EditorRoute
  '/faq': typeof FaqRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/screenshot-sizes/$store': typeof ScreenshotSizesStoreRoute
  '/guides/': typeof GuidesIndexRoute
  '/screenshot-sizes/': typeof ScreenshotSizesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/agents'
    | '/editor'
    | '/faq'
    | '/guides/$slug'
    | '/screenshot-sizes/$store'
    | '/guides/'
    | '/screenshot-sizes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/agents'
    | '/editor'
    | '/faq'
    | '/guides/$slug'
    | '/screenshot-sizes/$store'
    | '/guides'
    | '/screenshot-sizes'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/agents'
    | '/editor'
    | '/faq'
    | '/guides/$slug'
    | '/screenshot-sizes/$store'
    | '/guides/'
    | '/screenshot-sizes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AgentsRoute: typeof AgentsRoute
  EditorRoute: typeof EditorRoute
  FaqRoute: typeof FaqRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ScreenshotSizesStoreRoute: typeof ScreenshotSizesStoreRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ScreenshotSizesIndexRoute: typeof ScreenshotSizesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshot-sizes/': {
      id: '/screenshot-sizes/'
      path: '/screenshot-sizes'
      fullPath: '/screenshot-sizes/'
      preLoaderRoute: typeof ScreenshotSizesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshot-sizes/$store': {
      id: '/screenshot-sizes/$store'
      path: '/screenshot-sizes/$store'
      fullPath: '/screenshot-sizes/$store'
      preLoaderRoute: typeof ScreenshotSizesStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AgentsRoute: AgentsRoute,
  EditorRoute: EditorRoute,
  FaqRoute: FaqRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ScreenshotSizesStoreRoute: ScreenshotSizesStoreRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ScreenshotSizesIndexRoute: ScreenshotSizesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
